const root=document.documentElement;const themeToggle=document.querySelector('[data-theme-toggle]');const themeIcon=document.querySelector('[data-theme-icon]');const navToggle=document.querySelector('[data-nav-toggle]');const navPanel=document.querySelector('[data-nav-panel]');const header=document.querySelector('[data-header]');
function setTheme(theme){root.setAttribute('data-theme',theme);localStorage.setItem('theme',theme);if(themeIcon)themeIcon.textContent=theme==='dark'?'☀️':'🌙';}
(function initTheme(){const saved=localStorage.getItem('theme');const preferred=window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';setTheme(saved||preferred);})();
themeToggle?.addEventListener('click',()=>setTheme(root.getAttribute('data-theme')==='dark'?'light':'dark'));
function closeMenu(){navToggle?.classList.remove('is-open');navPanel?.classList.remove('is-open');document.body.classList.remove('menu-open');navToggle?.setAttribute('aria-expanded','false');navToggle?.setAttribute('aria-label','Open navigation menu');}
navToggle?.addEventListener('click',()=>{const open=!navPanel.classList.contains('is-open');navToggle.classList.toggle('is-open',open);navPanel.classList.toggle('is-open',open);document.body.classList.toggle('menu-open',open);navToggle.setAttribute('aria-expanded',String(open));navToggle.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu');});
navPanel?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const revealEls=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target);}})},{threshold:.1,rootMargin:'0px 0px -40px 0px'});revealEls.forEach(el=>io.observe(el));}else{revealEls.forEach(el=>el.classList.add('is-visible'));}
let last=0;window.addEventListener('scroll',()=>{const y=window.scrollY;header?.classList.toggle('is-scrolled',y>8);last=y;},{passive:true});
